apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-batch-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-batch-job
            image: my-batch-job-image
            command: ['sh', '-c', './batch-job-command']
