apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: send-slack
  namespace: argo
  annotations:
    workflows.argoproj.io/description: >-
      A template for sending slack notifications with workflow status details when the workflow begins and completes.
    workflows.argoproj.io/maintainer: '@courtneygreif'
    workflows.argoproj.io/tags: slack-workflow-notifications
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  templates:
    - name: send-completion
      inputs:
        parameters:
          - name: WORKFLOW_NAME
          - name: WORKFLOW_STATUS
          - name: SLACK_CHANNEL
      container:
        image: curlimages/curl
        imagePullPolicy: "Always"
        env:
          - name: WORKFLOW_ENV # Optional
            value: "qa"
          - name: WORKFLOW_CLOUD # Optional
            value: "aws"
          - name: CLOUD_REGION # Optional
            value: ""
          - name: ENV_DOMAIN # Optional
            value: "com"
          - name: SLACK_TOKEN
            value: YOUR_SLACK_TOKEN
        command:
          - sh
          - -c
        args:
          - |
            if [[ "{{ `{{inputs.parameters.WORKFLOW_STATUS}}` }}" == "Succeeded" ]]; then
            EMOJI=":celebrate:"
            COLOR="#00ff00"
            else
            EMOJI=":failed:"
            COLOR="#ff0000"
            fi
            curl -vvv -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-type: application/json" \
            --data "{\"token\": \"$SLACK_TOKEN\", \"channel\": \"{{ `{{inputs.parameters.SLACK_CHANNEL}}` }}\", \"text\" : \"Workflow {{ `{{inputs.parameters.WORKFLOW_STATUS}}` }}\", \"attachments\": [{\"color\": \"$COLOR\",\"blocks\": [ { \"type\": \"section\", \"fields\": [{ \"type\": \"mrkdwn\", \"text\": \"\"}] }, { \"type\": \"section\", \"fields\": [ { \"type\": \"mrkdwn\", \"text\": \"*Workflow Name:*\\n{{ `{{inputs.parameters.WORKFLOW_NAME}}` }}\" }, { \"type\": \"mrkdwn\", \"text\": \"*Workflow Outcome:*\\n{{ `{{inputs.parameters.WORKFLOW_STATUS}}` }} $EMOJI\" } ] } ] }] }" \
            https://slack.com/api/chat.postMessage
    
    - name: send-beginning
      inputs:
        parameters:
          - name: WORKFLOW_NAME
          - name: SLACK_CHANNEL
      container:
        image: curlimages/curl
        imagePullPolicy: "Always"
        env:
          - name: WORKFLOW_ENV # Optional
            value: "qa"
          - name: WORKFLOW_CLOUD # Optional
            value: "aws"
          - name: CLOUD_REGION # Optional
            value: "us-gov-west-1"
          - name: ENV_DOMAIN # Optional
            value: "com"
          - name: SLACK_TOKEN
            value: YOUR_SLACK_TOKEN
        command:
          - sh
          - -c
        args:
          - |
            curl -vvv -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-type: application/json" \
            --data "{\"token\": \"$SLACK_TOKEN\", \"channel\": \"{{ `{{inputs.parameters.SLACK_CHANNEL}}` }}\", \"text\" : \"Workflow {{ `{{inputs.parameters.WORKFLOW_NAME}}` }} beginning:star:\", \"attachments\": [{\"color\": \"#ADD8E6\",\"blocks\": [ { \"type\": \"section\", \"fields\": [{ \"type\": \"mrkdwn\", \"text\": \"\"}] } ] }]  }" \
            https://slack.com/api/chat.postMessage