apiVersion: v1
kind: Service
metadata:
  name: evidence-dev
  namespace: default
  labels:
    app.kubernetes.io/name: evidence-dev
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: postgres-psql
      protocol: TCP
      name: psql
  selector:
    app.kubernetes.io/name: evidence-dev
