apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-datagen-job
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:12-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgres-db -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: postgres-datagen-job
        image: datagen
        # command: ["psql"]
        command: ["python3", "user_payments_generator.py"]
        # args: ["-U", "postgres", "-h", "postgres-db", "-f", "/etc/go-loader/go-loader.sql"]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      restartPolicy: Never
  events:
  - type: Normal
    reason: postgres-db-started
    message: The postgres-db service has started
