apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-loader-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-loader
  template:
    metadata:
      labels:
        app: go-loader
    spec:
      containers:
      - name: go-loader
        image: go_loader:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_PORT
          volumeMounts:
          - name: go-loader-data
          mountPath: /data
        volumes:
        - name: go-loader-data
        persistentVolumeClaim:
        claimName: go-loader-pv-claim