apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-loader-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-loader
  template:
    metadata:
      labels:
        app: go-loader
    spec:
      initContainers:
    # Mounts the voulme as writable for the nonroot user (65532) in the final build image
      - name: chown-data
        image: busybox:latest
        command: ["chown", "-R", "65532:65532", "/data"]
        volumeMounts:
        - name: go-loader-data
          mountPath: /data
      containers:
      - name: go-loader
        image: go_loader:latest
        ports:  
        - containerPort: 8000
        volumeMounts:
        - name: go-loader-data
          mountPath: /data
        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
        env:
        - name: VOLUME_MOUNT_PATH
          value: "/data"
        - name: POSTGRES_USER
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
                secretKeyRef:
                  name: go-loader-secret
                  key: POSTGRES_PORT
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: go-loader-data
        persistentVolumeClaim:
          claimName: go-loader-pv-claim