apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: argo
  name: dbt-process-template
  annotations:
    workflows.argoproj.io/description: >-
      This workflow template will pull a repository from GitHub and run dbt commands on it.
    workflows.argoproj.io/maintainer: '@kcirtapfromspace'
    workflows.argoproj.io/maintainer_url: 'https://github.com/kcirtapfromspace/datatabase_thing'
    workflows.argoproj.io/version: '>= 3.3.6'
spec:
  templates:
  - name: dbt-process
    inputs:
      artifacts:
      - name: repo-data
        path: /opt/venv/
        s3:
          key: "{{`{{inputs.parameters.repo}}`}}/{{`{{inputs.parameters.branch}}`}}/{{ `{{workflow.uid}}` }}"
      parameters:
      - name: repo
      - name: branch
      - name: dbt-task
        default: "build"
      - name: dbt-project
        default: "lakehouse_demo"

    container:
      image: ghcr.io/kcirtapfromspace/database_thing/dbt:go-superduck732c059-push@sha256:6fff9776c3d993cc8e71e3e76665f6b4e278c5e34ef13fb8cc5aa651089636b7  # Replace with desired dbt Docker container image
      command: ["sh", "-c"]
      args: ["dbt {{ `{{inputs.parameters.dbt-task}}` }} ; sleep infinity"]
      # args: ["dbt {{ `{{inputs.parameters.dbt-task}}` }} --project-dir {{ `{{inputs.parameters.dbt-project}}` }}; sleep infinity"]
    resources:
      requests:
        memory: 250Mi
        cpu: 4m
    activeDeadlineSeconds: 300