apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: "deequ-quality-checks{{ .Release.Name }}"
spec:
  entrypoint: independent-run
  arguments:
    parameters:
      - name: database_user
        value: {{ .Values.workflow.database_user }}
      - name: database_password
        value: {{ .Values.workflow.database_password }}
      - name: database_host
        value: {{ .Values.workflow.database_host }}
      - name: database_port
        value: {{ .Values.workflow.database_port }}
      - name: database_name
        value: {{ .Values.workflow.database_name }}
  templates:
  - name: independent-run
    container:
      image: localhost:5000/deequ:local
      command: [python, "quality_checks/pydeequ/dyno_deequ.py"]
      args: []
      env:
      - name: database_user
        value: "{{ `{{ workflow.parameters.database_user}}` }}"
      - name: database_password
        value: "{{ `{{workflow.parameters.database_password}}` }}"
      - name: database_host
        value: "{{ `{{workflow.parameters.database_host}}` }}"
      - name: database_port
        value: "{{ `{{workflow.parameters.database_port}}` }}"
      - name: database_name
        value: "{{ `{{workflow.parameters.database_name}}` }}"
      imagePullPolicy: IfNotPresent
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion