apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: data-workflow
  annotations:
    workflows.argoproj.io/description: >-
      This workflow will pull a GitHub repository, and then run dbt commands on
      the repository. It will then send a Slack notification with the results of
      the workflow.
    workflows.argoproj.io/maintainer: '@kcirtapfromspace'
    workflows.argoproj.io/tags: data-workflow
    workflows.argoproj.io/version: '>= 3.0.0'
spec:
  serviceAccountName: argo-workflow
  entrypoint: dag
  onExit: exit-notification
  arguments:
    parameters:
    - name: repo
      value: "kcirtapfromspace/database_thing"  # Replace this with the actual repository URL
    - name: repo-branch
      value: "go-superduck"  # Replace this with the desired branch
  templates:
  - name: dag
    dag:
      tasks:
      - name: workflow-beginning
        templateRef:
          name: slack-notify-http
          template: send-beginning
        arguments:
          parameters:
          - name: WORKFLOW_NAME
            value: "{{ `{{workflow.name}}` }}"
          - name: SLACK_WEBHOOK_URL
            value: "https://hooks.slack.com/services/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"
      - name: pull-github-repo
        templateRef:
          name: pull-github-repo-template
          template: pull-github-repo
        dependencies: [workflow-beginning]
        arguments:
          parameters:
          - name: repo
            value: "{{ `{{workflow.parameters.repo}}` }}"
          - name: repo-branch
            value: "{{ `{{workflow.parameters.repo-branch}}` }}"
      - name: dbt-build
        templateRef:
          name: dbt-process-template
          template: dbt-process
        dependencies: [pull-github-repo]
        arguments:
          parameters:
          - name: repo
            value: "{{ `{{workflow.parameters.repo}}` }}"
          - name: repo-branch
            value: "{{ `{{workflow.parameters.repo-branch}}` }}"
  - name: exit-notification
    steps:
      - - name: exit-time
          templateRef:
            name: slack-notify-http
            template: send-completion
          arguments:
            parameters:
              - name: WORKFLOW_STATUS
                value: "{{ `{{workflow.status}}` }}"
              - name: WORKFLOW_NAME
                value: "{{ `{{workflow.name}}` }}"
              - name: SLACK_WEBHOOK_URL
                value: "https://hooks.slack.com/services/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"
