apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-psql
      protocol: TCP
      name: psql
  selector:
    app.kubernetes.io/name: postgres-db
