name: lakehouse
version: '1.0'
profile: lakehouse
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
model-paths:
  - models/users
  - models/payments
  - models/latest_payments
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: target
log-path: logs
packages-install-path: dbt_packages
clean-targets:
  - target
  - dbt_packages
  - logs


models:
  lakehouse:
    users:
      +materialized: view
      +directory: models/users
    payments:
      +materialized: view
      +directory: models/payments
