apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: py_app:latest
        ports:
        - containerPort: 5002
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_HOST
          value: "host"
        - name: POSTGRES_PORT
          value: "port"
        - name: POSTGRES_DBNAME
          value: "dbname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-gx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-gx
  template:
    metadata:
      labels:
        app: py-gx
    spec:
      containers:
      - name: py-gx
        image: py_ex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deequ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-deequ
  template:
    metadata:
      labels:
        app: py-deequ
    spec:
      containers:
      - name: py-deequ
        image: py_deequ
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt-argo
  template:
    metadata:
      labels:
        app: dbt-argo
    spec:
      containers:
      - name: dbt-argo
        image: dbt_argo