commonLabels:
  service: redpanda
tls:
  enabled: false 
console:
  enabled: true
  configmap:
    create: true
  secret:
    create: true
  deployment:
    create: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
storage:
  persistentVolume:
    enabled: true
    size: 5Gi
cluster:
  config:
    redpanda:
      enable_transctions: true
      enable_idempotence: true
      auto_create_topics_enabled: true