name: Build and Test

on: [push]

env:
  DOCKER_REGISTRY: kcirtapfromspace
  DOCKER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/go_loader:${{ env.DOCKER_IMAGE_TAG }}
        tags: ${{ env.DOCKER_REGISTRY }}/psql_db:${{ env.DOCKER_IMAGE_TAG }}
        tags: ${{ env.DOCKER_REGISTRY }}/pushup:${{ env.DOCKER_IMAGE_TAG }}
        tags: ${{ env.DOCKER_REGISTRY }}/py_app:${{ env.DOCKER_IMAGE_TAG }}

    - name: Test Go code
      working-directory: ops/dev-stack/go_loader
      run: go test ./...

    - name: Test Python code
      working-directory: ops/dev-stack/py_app
      run: |
        pip install -r requirements.txt
        python -m unittest discover

    - name: Deploy to development environment
      run: <your_deployment_command>

    - name: Notify team
      uses: <your_notification_action>
      with:
        message: Build and test completed successfully.
