name: Code Quality and Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover

    - name: Run code quality checks
      run: |
        flake8 .
        pylint --rcfile=.pylintrc .
        
    - name: Generate documentation
      run: |
        sphinx-build -b html docs/ docs/_build