name: Docker
on:
  push:
    branches:
      - main  

env:
  DOCKER_REGISTRY: kcirtapfromspace
  DOCKER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/go_loader:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/psql_db:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/pushup:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/py_app:${{ env.DOCKER_IMAGE_TAG }}

    # - name: Deploy to development environment
    #   run: <your_deployment_command>

      - name: Run security scans
        uses: docker://aquasec/trivy:0.17.0
        with:
          args: --exit-code 0 --severity CRITICAL --quiet /app
