# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/ops/dev-stack/go_loader/src
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: ${{ github.workspace }}/ops/dev-stack/go_loader/src

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
      env:
        GOPATH: ${{ github.workspace }}
        GOBIN: ${{ github.workspace }}/bin


    - name: Build
      run: go build -v main.go

    - name: Test
      run: go test -v ops/dev-stack/go_loader/src/main.go
