name: grype scan & syft sbom

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      strategy:
        matrix:
          dockerfile: 
          - dbt
          - datagen
          - debezium
          - deequ
          - go_loader
          - gx

      steps:
        - name: Generate SBOM
          uses: anchore/sbom-action@v0
          with:
            image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.dockerfile }}
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
    
        - name:  invoke the Grype scanner
          uses: anchore/scan-action@v3
          with:
            image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.dockerfile }}
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
